{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D\n",
    "from keras.layers import Activation, Dropout, Flatten, Dense\n",
    "from keras import backend as K\n",
    "import math\n",
    "\n",
    "# dimensions of our images.\n",
    "img_width, img_height = 300, 300\n",
    "\n",
    "train_data_dir = 'data/train'\n",
    "validation_data_dir = 'data/test'\n",
    "nb_train_samples = 3000\n",
    "nb_validation_samples = 300\n",
    "epochs = 5\n",
    "batch_size = 300"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "input_shape = (img_height, img_width, 3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "## Adding convolutional layers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "model = Sequential()\n",
    "model.add(Conv2D(10, (3, 3), activation = 'relu', input_shape=input_shape))\n",
    "model.add(MaxPooling2D(pool_size=(2, 2)))\n",
    "model.add(Conv2D(20, (3, 3), activation = 'relu'))\n",
    "model.add(MaxPooling2D(pool_size=(2, 2)))\n",
    "model.add(Flatten())\n",
    "model.add(Dense(32, activation = 'relu'))\n",
    "model.add(Dense(2))\n",
    "model.add(Activation('softmax'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "conv2d_1 (Conv2D)            (None, 298, 298, 10)      280       \n",
      "_________________________________________________________________\n",
      "max_pooling2d_1 (MaxPooling2 (None, 149, 149, 10)      0         \n",
      "_________________________________________________________________\n",
      "conv2d_2 (Conv2D)            (None, 147, 147, 20)      1820      \n",
      "_________________________________________________________________\n",
      "max_pooling2d_2 (MaxPooling2 (None, 73, 73, 20)        0         \n",
      "_________________________________________________________________\n",
      "flatten_1 (Flatten)          (None, 106580)            0         \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 32)                3410592   \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 2)                 66        \n",
      "_________________________________________________________________\n",
      "activation_1 (Activation)    (None, 2)                 0         \n",
      "=================================================================\n",
      "Total params: 3,412,758\n",
      "Trainable params: 3,412,758\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "model.compile(loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 3000 images belonging to 2 classes.\n",
      "Found 300 images belonging to 2 classes.\n"
     ]
    }
   ],
   "source": [
    "# this is the augmentation configuration we will use for training\n",
    "train_datagen = ImageDataGenerator(\n",
    "    rescale=1. / 255,\n",
    "    shear_range=0.2,\n",
    "    zoom_range=0.2,\n",
    "    horizontal_flip=True)\n",
    "\n",
    "# this is the augmentation configuration we will use for testing:\n",
    "# only rescaling\n",
    "test_datagen = ImageDataGenerator(rescale=1. / 255)\n",
    "\n",
    "train_generator = train_datagen.flow_from_directory(\n",
    "    train_data_dir,\n",
    "    target_size=(img_width, img_height),\n",
    "    batch_size=batch_size,\n",
    "    class_mode='categorical')\n",
    "\n",
    "validation_generator = test_datagen.flow_from_directory(\n",
    "    validation_data_dir,\n",
    "    target_size=(img_width, img_height),\n",
    "    batch_size=batch_size,\n",
    "    class_mode='categorical')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "10/10 [==============================] - 61s - loss: 1.1534 - acc: 0.4970 - val_loss: 0.6932 - val_acc: 0.5000\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n",
      "Epoch 2/5\n",
      "10/10 [==============================] - 57s - loss: 0.6919 - acc: 0.5320 - val_loss: 0.6892 - val_acc: 0.6100\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n",
      "Epoch 3/5\n",
      "10/10 [==============================] - 57s - loss: 0.6903 - acc: 0.5540 - val_loss: 0.6884 - val_acc: 0.5733\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n",
      "Epoch 4/5\n",
      "10/10 [==============================] - 57s - loss: 0.6811 - acc: 0.5790 - val_loss: 0.6797 - val_acc: 0.5833\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n",
      "Epoch 5/5\n",
      "10/10 [==============================] - 56s - loss: 0.6799 - acc: 0.5980 - val_loss: 0.6779 - val_acc: 0.6267\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.History at 0x7fec494641d0>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.fit_generator(\n",
    "    train_generator,\n",
    "    steps_per_epoch= math.ceil(nb_train_samples / batch_size),\n",
    "    epochs=epochs,\n",
    "    validation_data=validation_generator,\n",
    "    validation_steps=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "### More than 60% now.\n",
    "\n",
    "### Let's add more convolutions and some dropout/batch normalisation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting webserver from: /anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:44] \"GET /model HTTP/1.1\" 200 4780 0.002506\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:44] \"GET /inputs HTTP/1.1\" 200 2980 0.000894\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4757.jpg HTTP/1.1\" 200 33208 0.000788\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4571.jpg HTTP/1.1\" 200 34545 0.000764\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4930.jpg HTTP/1.1\" 200 42671 0.206326\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4677.jpg HTTP/1.1\" 200 65093 0.207813\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4697.jpg HTTP/1.1\" 200 53641 0.210361\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4563.jpg HTTP/1.1\" 200 50804 0.225656\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4867.jpg HTTP/1.1\" 200 45026 0.001328\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4490.jpg HTTP/1.1\" 200 41287 0.000932\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:45] \"GET /input-file/dog.4631.jpg HTTP/1.1\" 200 33514 0.000925\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.47.jpg HTTP/1.1\" 200 31144 0.001287\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4820.jpg HTTP/1.1\" 200 32375 0.000786\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4841.jpg HTTP/1.1\" 200 44430 0.000778\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4900.jpg HTTP/1.1\" 200 31189 0.000860\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4891.jpg HTTP/1.1\" 200 52381 0.000817\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4737.jpg HTTP/1.1\" 200 53085 0.000818\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4703.jpg HTTP/1.1\" 200 41270 0.000795\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4633.jpg HTTP/1.1\" 200 33191 0.000749\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4936.jpg HTTP/1.1\" 200 32084 0.000754\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4799.jpg HTTP/1.1\" 200 31245 0.000748\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4879.jpg HTTP/1.1\" 200 40134 0.000780\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4857.jpg HTTP/1.1\" 200 35539 0.000744\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4874.jpg HTTP/1.1\" 200 54612 0.000762\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:46] \"GET /input-file/dog.4831.jpg HTTP/1.1\" 200 44357 0.000931\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4894.jpg HTTP/1.1\" 200 63023 0.000791\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4673.jpg HTTP/1.1\" 200 45894 0.000803\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4497.jpg HTTP/1.1\" 200 58859 0.001135\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4627.jpg HTTP/1.1\" 200 54158 0.000923\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4728.jpg HTTP/1.1\" 200 45550 0.000804\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.463.jpg HTTP/1.1\" 200 47849 0.000829\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4629.jpg HTTP/1.1\" 200 40321 0.000776\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:47] \"GET /input-file/dog.4623.jpg HTTP/1.1\" 200 43939 0.000975\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.5026.jpg HTTP/1.1\" 200 32091 0.001039\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4559.jpg HTTP/1.1\" 200 42616 0.000762\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4581.jpg HTTP/1.1\" 200 40887 0.000768\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4570.jpg HTTP/1.1\" 200 34195 0.000755\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.456.jpg HTTP/1.1\" 200 43455 0.000816\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4955.jpg HTTP/1.1\" 200 33073 0.000749\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4680.jpg HTTP/1.1\" 200 37866 0.000760\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.5016.jpg HTTP/1.1\" 200 31618 0.000794\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4492.jpg HTTP/1.1\" 200 38892 0.000764\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4568.jpg HTTP/1.1\" 200 47972 0.000762\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4657.jpg HTTP/1.1\" 200 35030 0.000767\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4617.jpg HTTP/1.1\" 200 33628 0.000800\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4604.jpg HTTP/1.1\" 200 47028 0.000797\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:48] \"GET /input-file/dog.4742.jpg HTTP/1.1\" 200 53921 0.000799\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.5023.jpg HTTP/1.1\" 200 34095 0.000802\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.5011.jpg HTTP/1.1\" 200 38492 0.000759\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4653.jpg HTTP/1.1\" 200 36417 0.000758\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4901.jpg HTTP/1.1\" 200 35720 0.000756\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4808.jpg HTTP/1.1\" 200 35229 0.000905\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4624.jpg HTTP/1.1\" 200 34336 0.000769\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4844.jpg HTTP/1.1\" 200 31142 0.000795\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4911.jpg HTTP/1.1\" 200 42302 0.000896\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4760.jpg HTTP/1.1\" 200 40303 0.000775\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.450.jpg HTTP/1.1\" 200 42976 0.000754\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4923.jpg HTTP/1.1\" 200 35047 0.000772\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4814.jpg HTTP/1.1\" 200 36414 0.000761\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:49] \"GET /input-file/dog.4675.jpg HTTP/1.1\" 200 32594 0.000759\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.451.jpg HTTP/1.1\" 200 38938 0.000916\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4905.jpg HTTP/1.1\" 200 60473 0.000967\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4595.jpg HTTP/1.1\" 200 31319 0.000892\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4567.jpg HTTP/1.1\" 200 42370 0.000832\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4682.jpg HTTP/1.1\" 200 37728 0.000758\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4953.jpg HTTP/1.1\" 200 39815 0.000788\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4686.jpg HTTP/1.1\" 200 43578 0.000796\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4685.jpg HTTP/1.1\" 200 40889 0.000765\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4997.jpg HTTP/1.1\" 200 48146 0.000755\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4993.jpg HTTP/1.1\" 200 31775 0.000727\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4683.jpg HTTP/1.1\" 200 34905 0.000750\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4704.jpg HTTP/1.1\" 200 33189 0.000743\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:50] \"GET /input-file/dog.4586.jpg HTTP/1.1\" 200 48325 0.000748\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4681.jpg HTTP/1.1\" 200 32865 0.000884\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4793.jpg HTTP/1.1\" 200 41646 0.000825\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.5002.jpg HTTP/1.1\" 200 31149 0.001003\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4709.jpg HTTP/1.1\" 200 35590 0.000949\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4763.jpg HTTP/1.1\" 200 32296 0.001080\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.467.jpg HTTP/1.1\" 200 32093 0.000742\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4782.jpg HTTP/1.1\" 200 39375 0.000799\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4619.jpg HTTP/1.1\" 200 33187 0.000738\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4951.jpg HTTP/1.1\" 200 32863 0.000742\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4769.jpg HTTP/1.1\" 200 66728 0.000964\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4880.jpg HTTP/1.1\" 200 40941 0.000906\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4696.jpg HTTP/1.1\" 200 32993 0.000739\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4878.jpg HTTP/1.1\" 200 40232 0.000755\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4754.jpg HTTP/1.1\" 200 36206 0.000763\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:51] \"GET /input-file/dog.4668.jpg HTTP/1.1\" 200 31093 0.000723\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4781.jpg HTTP/1.1\" 200 42627 0.001269\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4865.jpg HTTP/1.1\" 200 40386 0.000805\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4875.jpg HTTP/1.1\" 200 32849 0.000775\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.5019.jpg HTTP/1.1\" 200 38592 0.000753\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4925.jpg HTTP/1.1\" 200 34110 0.000747\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4876.jpg HTTP/1.1\" 200 32464 0.000792\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4833.jpg HTTP/1.1\" 200 37743 0.005468\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4672.jpg HTTP/1.1\" 200 43155 0.000822\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.475.jpg HTTP/1.1\" 200 34282 0.000917\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4812.jpg HTTP/1.1\" 200 31094 0.000735\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4804.jpg HTTP/1.1\" 200 40212 0.000795\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:52] \"GET /input-file/dog.4829.jpg HTTP/1.1\" 200 33999 0.001088\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.470.jpg HTTP/1.1\" 200 36847 0.000833\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.458.jpg HTTP/1.1\" 200 37876 0.000730\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4496.jpg HTTP/1.1\" 200 40355 0.000897\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4942.jpg HTTP/1.1\" 200 36133 0.000749\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4826.jpg HTTP/1.1\" 200 58289 0.000754\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4719.jpg HTTP/1.1\" 200 63708 0.000757\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.491.jpg HTTP/1.1\" 200 52778 0.000742\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4907.jpg HTTP/1.1\" 200 37722 0.000788\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4735.jpg HTTP/1.1\" 200 49322 0.000770\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4852.jpg HTTP/1.1\" 200 35178 0.000727\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4614.jpg HTTP/1.1\" 200 55075 0.001134\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4918.jpg HTTP/1.1\" 200 49015 0.001253\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4835.jpg HTTP/1.1\" 200 71070 0.000813\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4965.jpg HTTP/1.1\" 200 35125 0.000799\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:53] \"GET /input-file/dog.4946.jpg HTTP/1.1\" 200 57698 0.000791\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.494.jpg HTTP/1.1\" 200 42025 0.000767\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4608.jpg HTTP/1.1\" 200 32481 0.000881\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4885.jpg HTTP/1.1\" 200 45546 0.000826\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4748.jpg HTTP/1.1\" 200 38927 0.000807\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4935.jpg HTTP/1.1\" 200 32963 0.000752\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4744.jpg HTTP/1.1\" 200 38023 0.000828\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4916.jpg HTTP/1.1\" 200 32468 0.000782\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4768.jpg HTTP/1.1\" 200 38789 0.000771\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4602.jpg HTTP/1.1\" 200 44729 0.002075\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4937.jpg HTTP/1.1\" 200 33027 0.000735\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4849.jpg HTTP/1.1\" 200 36263 0.000742\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4656.jpg HTTP/1.1\" 200 48715 0.000773\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.4664.jpg HTTP/1.1\" 200 33554 0.000744\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:54] \"GET /input-file/dog.471.jpg HTTP/1.1\" 200 42455 0.000751\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4861.jpg HTTP/1.1\" 200 39703 0.000743\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4713.jpg HTTP/1.1\" 200 49204 0.000765\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4578.jpg HTTP/1.1\" 200 38845 0.000933\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4647.jpg HTTP/1.1\" 200 33927 0.000760\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4579.jpg HTTP/1.1\" 200 34110 0.000769\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4940.jpg HTTP/1.1\" 200 42801 0.000782\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4717.jpg HTTP/1.1\" 200 45649 0.000752\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4821.jpg HTTP/1.1\" 200 53899 0.000758\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4679.jpg HTTP/1.1\" 200 46518 0.001024\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4747.jpg HTTP/1.1\" 200 53885 0.000962\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4959.jpg HTTP/1.1\" 200 40237 0.001060\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:55] \"GET /input-file/dog.4729.jpg HTTP/1.1\" 200 41250 0.000764\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4723.jpg HTTP/1.1\" 200 33485 0.000829\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4562.jpg HTTP/1.1\" 200 35690 0.000760\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.484.jpg HTTP/1.1\" 200 41534 0.000778\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4684.jpg HTTP/1.1\" 200 33546 0.000770\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4727.jpg HTTP/1.1\" 200 39892 0.000801\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4870.jpg HTTP/1.1\" 200 35671 0.001093\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4817.jpg HTTP/1.1\" 200 34810 0.000795\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4584.jpg HTTP/1.1\" 200 31955 0.000754\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4846.jpg HTTP/1.1\" 200 35640 0.000780\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4642.jpg HTTP/1.1\" 200 33264 0.000808\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:07:56] \"GET /input-file/dog.4996.jpg HTTP/1.1\" 200 36660 0.000749\n",
      "[2017-09-10 05:08:01,254] ERROR in app: Exception on /predict/dog.4907.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 127, in get_prediction\n",
      "    input_img = load_img(input_path, single_input_shape, grayscale=is_grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/util.py\", line 27, in load_img\n",
      "    img = image.load_img(input_path, target_size=target_shape, grayscale=grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/keras/preprocessing/image.py\", line 322, in load_img\n",
      "    img = pil_image.open(path)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 2282, in open\n",
      "    fp = builtins.open(filename, \"rb\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'dog.4907.jpg'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:01] \"GET /predict/dog.4907.jpg HTTP/1.1\" 500 444 0.096861\n",
      "/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/layer_result_generators.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor(\"co..., inputs=Tensor(\"co...)`\n",
      "  output=model.get_layer(layer_name).output\n",
      "[2017-09-10 05:08:01,378] ERROR in app: Exception on /layer/conv2d_1/dog.4907.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_1_0_dog.4907.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:01] \"GET /layer/conv2d_1/dog.4907.jpg HTTP/1.1\" 500 444 0.081486\n",
      "/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/layer_result_generators.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor(\"ma..., inputs=Tensor(\"co...)`\n",
      "  output=model.get_layer(layer_name).output\n",
      "[2017-09-10 05:08:05,136] ERROR in app: Exception on /layer/max_pooling2d_1/dog.4907.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_1_0_dog.4907.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:05] \"GET /layer/max_pooling2d_1/dog.4907.jpg HTTP/1.1\" 500 444 0.025072\n",
      "[2017-09-10 05:08:06,581] ERROR in app: Exception on /layer/conv2d_2/dog.4907.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_2_0_dog.4907.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:06] \"GET /layer/conv2d_2/dog.4907.jpg HTTP/1.1\" 500 444 0.027250\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:14] \"GET / HTTP/1.1\" 304 240 0.001325\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:15] \"GET /model HTTP/1.1\" 200 4780 0.002071\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:15] \"GET /inputs HTTP/1.1\" 200 2980 0.000787\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:15] \"GET /favicon.ico HTTP/1.1\" 200 16208 0.001332\n",
      "[2017-09-10 05:08:22,623] ERROR in app: Exception on /predict/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 127, in get_prediction\n",
      "    input_img = load_img(input_path, single_input_shape, grayscale=is_grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/util.py\", line 27, in load_img\n",
      "    img = image.load_img(input_path, target_size=target_shape, grayscale=grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/keras/preprocessing/image.py\", line 322, in load_img\n",
      "    img = pil_image.open(path)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 2282, in open\n",
      "    fp = builtins.open(filename, \"rb\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'dog.4677.jpg'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:22] \"GET /predict/dog.4677.jpg HTTP/1.1\" 500 444 0.002353\n",
      "[2017-09-10 05:08:22,653] ERROR in app: Exception on /layer/max_pooling2d_2/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_2_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:22] \"GET /layer/max_pooling2d_2/dog.4677.jpg HTTP/1.1\" 500 444 0.028376\n",
      "[2017-09-10 05:08:24,649] ERROR in app: Exception on /layer/conv2d_2/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_2_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:24] \"GET /layer/conv2d_2/dog.4677.jpg HTTP/1.1\" 500 444 0.026345\n",
      "[2017-09-10 05:08:26,137] ERROR in app: Exception on /layer/max_pooling2d_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_1_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:26] \"GET /layer/max_pooling2d_1/dog.4677.jpg HTTP/1.1\" 500 444 0.024666\n",
      "/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/layer_result_generators.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor(\"fl..., inputs=Tensor(\"co...)`\n",
      "  output=model.get_layer(layer_name).output\n",
      "[2017-09-10 05:08:42,519] ERROR in app: Exception on /layer/flatten_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 109, in get_layer_outputs\n",
      "    for z in range(0, layer_outputs.shape[2]):\n",
      "IndexError: tuple index out of range\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:42] \"GET /layer/flatten_1/dog.4677.jpg HTTP/1.1\" 500 444 0.027810\n",
      "[2017-09-10 05:08:43,758] ERROR in app: Exception on /layer/max_pooling2d_2/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_2_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:43] \"GET /layer/max_pooling2d_2/dog.4677.jpg HTTP/1.1\" 500 444 0.026781\n",
      "/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/layer_result_generators.py:7: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor(\"de..., inputs=Tensor(\"co...)`\n",
      "  output=model.get_layer(layer_name).output\n",
      "[2017-09-10 05:08:44,811] ERROR in app: Exception on /layer/dense_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 109, in get_layer_outputs\n",
      "    for z in range(0, layer_outputs.shape[2]):\n",
      "IndexError: tuple index out of range\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:44] \"GET /layer/dense_1/dog.4677.jpg HTTP/1.1\" 500 444 0.031298\n",
      "[2017-09-10 05:08:50,918] ERROR in app: Exception on /layer/max_pooling2d_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_1_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:50] \"GET /layer/max_pooling2d_1/dog.4677.jpg HTTP/1.1\" 500 444 0.024629\n",
      "[2017-09-10 05:08:52,869] ERROR in app: Exception on /layer/conv2d_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_1_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:08:52] \"GET /layer/conv2d_1/dog.4677.jpg HTTP/1.1\" 500 444 0.026274\n",
      "[2017-09-10 05:09:46,596] ERROR in app: Exception on /layer/max_pooling2d_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_1_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:09:46] \"GET /layer/max_pooling2d_1/dog.4677.jpg HTTP/1.1\" 500 444 0.024141\n",
      "[2017-09-10 05:09:47,920] ERROR in app: Exception on /layer/conv2d_1/dog.4677.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_1_0_dog.4677.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:09:47] \"GET /layer/conv2d_1/dog.4677.jpg HTTP/1.1\" 500 444 0.024115\n",
      "[2017-09-10 05:10:38,525] ERROR in app: Exception on /predict/dog.4729.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 127, in get_prediction\n",
      "    input_img = load_img(input_path, single_input_shape, grayscale=is_grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/util.py\", line 27, in load_img\n",
      "    img = image.load_img(input_path, target_size=target_shape, grayscale=grayscale)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/keras/preprocessing/image.py\", line 322, in load_img\n",
      "    img = pil_image.open(path)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 2282, in open\n",
      "    fp = builtins.open(filename, \"rb\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'dog.4729.jpg'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:10:38] \"GET /predict/dog.4729.jpg HTTP/1.1\" 500 444 0.002506\n",
      "[2017-09-10 05:10:38,549] ERROR in app: Exception on /layer/conv2d_1/dog.4729.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_1_0_dog.4729.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:10:38] \"GET /layer/conv2d_1/dog.4729.jpg HTTP/1.1\" 500 444 0.022655\n",
      "[2017-09-10 05:10:40,011] ERROR in app: Exception on /layer/max_pooling2d_1/dog.4729.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/max_pooling2d_1_0_dog.4729.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:10:40] \"GET /layer/max_pooling2d_1/dog.4729.jpg HTTP/1.1\" 500 444 0.023244\n",
      "[2017-09-10 05:10:41,191] ERROR in app: Exception on /layer/conv2d_1/dog.4729.jpg [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/quiver_engine/server.py\", line 119, in get_layer_outputs\n",
      "    imsave(filename, deprocessed)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/scipy/misc/pilutil.py\", line 197, in imsave\n",
      "    im.save(name)\n",
      "  File \"/anaconda/envs/py35/lib/python3.5/site-packages/PIL/Image.py\", line 1695, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './tmp/conv2d_1_0_dog.4729.jpg.png'\n",
      "::ffff:60.241.45.37 - - [2017-09-10 05:10:41] \"GET /layer/conv2d_1/dog.4729.jpg HTTP/1.1\" 500 444 0.022298\n"
     ]
    }
   ],
   "source": [
    "from quiver_engine import server\n",
    "server.launch(model,  input_folder='./data/test/dogs')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
